# Use postgres/example user/password credentials
version: '1.0'
services:
  api:
    image: micro_python:1.0.0
    command: sh -c "sleep 20 && gunicorn main:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - 5000:5432
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080